### ISSUE TITLE
Change timeout for slow job allocations

### ISSUE THREAD

**Issue by chun9l** [UM-Bridge/umbridge#35]
In the LoadBalancer implementation, a URL to the compute node will be returned after submitting the model SLURM script, but there is a timeout while waiting for this. Currently, the countdown for the timeout begins the moment the job is submitted, which means slow job allocation will be an issue.

**Comment by linusseelinger** [comment]
New plan: Get rid of timeouts since we don't know how long a job may take to submit on a cluster. Better to get stuck than to unnecessarily kill users' runs.
