### ISSUE TITLE
Shut down Hyperqueue server automatically after program stops

### ISSUE THREAD

**Issue by chun9l** [UM-Bridge/umbridge#38]
A Hyperqueue server starts whenever the loadbalancer executable is called, but it will continue to run after the program is killed. Subsequent calls will yield a warning about the existing Hyperqueue server. This does not break anything though.

**Comment by linusseelinger** [comment]
Possible approach: Try and stop hyperqueue before starting a new instance on loadbalancer launch.

**Comment by linusseelinger** [comment]
Solved by #45
