### ISSUE TITLE
Multiple allocation queues create too many SLURM jobs

### ISSUE THREAD

**Issue by Schlevidon** [UM-Bridge/umbridge#40]
In the current setup multiple allocation queues are used (at least two - one to determine the model names and one for each model). It seems like whenever HQ decides to add a new allocation to meet the current demand, all allocation queues create a new SLURM job. The result is that more SLURM jobs/HQ workers are created than necessary.

It might be best to have one shared allocation queue for all models to avoid wasting resources.

**Comment by Schlevidon** [comment]
Low priority at the moment, but would be nice to fix in the future for better performance.

**Comment by linusseelinger** [comment]
Should be enough to only start hyperqueue and allocation queue once at load balancer start, right?
